apiVersion: v1
kind: Service
metadata:
  name: solar-system-service
  namespace: solar-system
spec:
  type: NodePort
  selector:
    app: solar-system
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # nodePort removed to avoid potential conflicts
